### ISSUE TITLE
Loader issue

### ISSUE THREAD

**Issue by tanies** [noname0310/babylon-mmd-template#1]
As shown in Figure 1, when I modify the code in the figure and introduce. pmx or. pmd files, an error will be reported at sceneLoading (see Figure 2). After checking, the getDefaultPlugin method does not return default plugin information. This is the first time I have encountered such a project, please provide assistance.
<img width="844" alt="image" src="https://github.com/user-attachments/assets/fc9b5dda-76a1-4a8f-9421-fd97639a02e5" />

<img width="771" alt="image" src="https://github.com/user-attachments/assets/56d4e28f-0a21-4b72-88eb-96a7efa08135" />

**Comment by tanies** [comment]
Find the reason and release according to the comments
import "babylon-mmd/esm/Loader/pmdLoader";

**Comment by noname0310** [comment]
Good to hear it worked for you. If you have any further questions, please open an issue.
